name: doggo_friends
description: App that lets you search and adopt dogs.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter:  "6.0.0"

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf

  assets:
    - assets/dogs.json
    - images/profile_header_background.jpg