name: doggo_friends
description: App that lets you search and adopt dogs.

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "^0.2.3"
  firebase_auth: "^0.5.10"
  google_sign_in: "^3.0.3+1"
  cloud_firestore: "^0.7.2"
  font_awesome_flutter:  "^6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf

  assets:
    - assets/dogs.json
    - images/profile_header_background.jpg
